---
# - ansible.builtin.import_playbook: "./create-networks.yaml"
- name: Create Q1 topology
  hosts: localhost
  become: yes
  gather_facts: yes
  vars:
    disk_dir: /var/lib/libvirt/images
    sub_dir: "templates"
    state: running
    # vm_name: "{{ vm_name }}"
    ram: 1048576
    vcpu: 1
    disk_space: 10G
    # networks: "{{ networks }}"
  
  tasks:
    - name: Make PublicNet
      ansible.builtin.import_tasks: "./create-networks.yaml"
      vars:
        bridge_name: PublicNet
        ip_subnet: 192.166.12.1
        ip_start: 192.166.12.2
        ip_end: 192.166.12.254

    - name: Make PrivateNet
      ansible.builtin.import_tasks: "./create-networks.yaml"
      vars:
        bridge_name: PrivateNet
        ip_subnet: 192.167.12.1
        ip_start: 192.167.12.2
        ip_end: 192.167.12.254
    - name: Make Router VM
      ansible.builtin.import_tasks: "./create-vm.yaml"
      vars:
        vm_name: 'RouterVM'
        enable_public: true
        enable_private: true
    
    - name: Make Client VM
      ansible.builtin.import_tasks: "./create-vm.yaml"
      vars:
        vm_name: 'Client'
        enable_public: true
        enable_private: false
    
    
    - name: Make Server 1
      ansible.builtin.import_tasks: "./create-vm.yaml"
      vars:
        vm_name: 'Server1'
        enable_public: false
        enable_private: true

    
    - name: Make Server 2
      ansible.builtin.import_tasks: "./create-vm.yaml"
      vars:
        vm_name: 'Server2'
        enable_public: false
        enable_private: true
