#- name: Log system performance load averages
---
- hosts: localhost
  tasks:
  - name: Modify permissions
    file:
      path: /home/vmadm/megh/hw2/kvmlab/system-monitor.sh
      mode: 0777
  - name: Run bash script
    shell:
      cmd: /home/vmadm/megh/hw2/kvmlab/system-monitor.sh 60 600
    register: output
    become: yes
  - name: Make destination directory
    ansible.builtin.file:
      path: /var/customlogs/logs
      state: directory
    become: yes
  - name: Make a file if it does not exist
    ansible.builtin.copy:
      content: ""
      dest: /var/customlogs/logs/log.csv
  - name: Add the static header entry
    shell:
      cmd: "echo hostname,cpu1min,cpu5min,cpu15min >> /var/customlogs/logs/log.csv"
  - name: Register the line to the log
    ansible.builtin.lineinfile:
      path: /var/customlogs/logs/log.csv
      insertafter: EOF
      line: "{% for l in output.stdout_lines %}{{ l }}\n{% endfor %}"
#    with_items: "{{ output.stdout_lines }}"

- hosts: monitored
  vars:
    hostn1: "{{ ansible_hostname }}"
  tasks:
  - name: Copy
    copy:
      src: /home/vmadm/megh/hw2/kvmlab/system-monitor-vms.sh
      dest: /root
      mode: 0777
  - name: Run bash script
    shell:
      cmd: /root/system-monitor-vms.sh 60 600
    register: output
  - name: Make destination directory
    ansible.builtin.file:
      path: /var/customlogs/logs
      state: directory
    become: yes
  - name: Make a file if it does not exist
    ansible.builtin.copy:
      content: ""
      dest: /var/customlogs/logs/log.csv
  - name: Register the line to the log
    ansible.builtin.lineinfile:
      path: /var/customlogs/logs/log.csv
      insertafter: EOF
      line: "{% for l in output.stdout_lines %}{{ l }}\n{% endfor %}"
  - name: Fetch remotely logged files
    ansible.builtin.fetch:
      src: /var/customlogs/logs/log.csv
      dest: /var/customlogs/logs/{{ hostn1 }}.csv
      #dest: /var/customlogs/logs/temp
      flat: yes
#  - name: Unify all content
#    ansible.builtin.blockinfile:
#      path: /var/customlogs/logs/log
#      block:  "{{lookup('file', '/var/customlogs/logs/' + ansible_hostname) }}"
#      #block: "{{ lookup('file', '/var/customlogs/logs/temp') }}"
#      insertafter: EOF

  - name: Collate all CSVs
    shell:
      cmd: "cat /var/customlogs/logs/{{ hostn1 }}.csv >> /var/customlogs/logs/log.csv"
    delegate_to: localhost
